### ISSUE TITLE
TypeError: train() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by aswa123** [Res2Net/Res2Net-maskrcnn#3]
Hello Sir,
Can you please help me with this problem.
I tried many ways but I cannot success in that.
Error shows in line 160.
Thank you.

**Comment by gasvn** [comment]
Please show me your error message so I can help you.

**Comment by aswa123** [comment]
Traceback (most recent call last):
  File "/home/swap/miniconda3/envs/Res2Net-maskrcnn-master/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3427, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-3f8b428bf94e>", line 1, in <module>
    runfile('/home/swap/Downloads/Res2Net-maskrcnn-master/tools/train_net.py', args=['--config-file', 'configs/pytorch_mask_rcnn_R2_50_s4_FPN_2x.yaml', 'SOLVER.IMS_PER_BATCH', '2', 'SOLVER.BASE_LR', '0.0025', 'SOLVER.MAX_ITER', '7200', 'SOLVER.STEPS', '(480000, 640000)', 'TEST.IMS_PER_BATCH', '1'], wdir='/home/swap/Downloads/Res2Net-maskrcnn-master')
  File "/home/swap/.local/share/JetBrains/Toolbox/apps/PyCharm-C/ch-0/202.7660.27/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/swap/.local/share/JetBrains/Toolbox/apps/PyCharm-C/ch-0/202.7660.27/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/swap/Downloads/Res2Net-maskrcnn-master/tools/train_net.py", line 167, in <module>
    main()
  File "/home/swap/Downloads/Res2Net-maskrcnn-master/tools/train_net.py", line 160, in main
    model = train(cfg, args.local_rank, args.distributed)
TypeError: train() takes 2 positional arguments but 3 were given

**Comment by gasvn** [comment]
Do you use the following command to train the model?
export NGPUS=8
python -m torch.distributed.launch --nproc_per_node=$NGPUS /path_to_maskrcnn_benchmark/tools/train_net.py --config-file "configs/pytorch_mask_rcnn_R2_50_s4_FPN_2x.yaml"

**Comment by gasvn** [comment]
The train function is `def train(cfg, local_rank, distributed):` And it should receive 3 arguments instead of 2. I didn't find this bug when running this repo.

**Comment by gasvn** [comment]
How you install this repo first following https://github.com/Res2Net/Res2Net-maskrcnn/blob/master/INSTALL.md ?

**Comment by gasvn** [comment]
![image](https://user-images.githubusercontent.com/20515144/109001175-94bb0080-76df-11eb-9543-4deee1461bc4.png)

**Comment by aswa123** [comment]
python tools/train_net.py --config-file "configs/pytorch_mask_rcnn_R2_50_s4_FPN_2x.yaml" SOLVER.IMS_PER_BATCH 2 SOLVER.BASE_LR 0.0025 SOLVER.MAX_ITER 720000 SOLVER.STEPS "(480000, 640000)" TEST.IMS_PER_BATCH 1

> Do you use the following command to train the model?
> export NGPUS=8
> python -m torch.distributed.launch --nproc_per_node=$NGPUS /path_to_maskrcnn_benchmark/tools/train_net.py --config-file "configs/pytorch_mask_rcnn_R2_50_s4_FPN_2x.yaml"

**Comment by aswa123** [comment]
> How you install this repo first following https://github.com/Res2Net/Res2Net-maskrcnn/blob/master/INSTALL.md ?

yes.

**Comment by gasvn** [comment]
You can try the distributed training mode. I didn't use the python tools/train_net.py --config-file "configs/pytorch_mask_rcnn_R2_50_s4_FPN_2x.yaml" SOLVER.IMS_PER_BATCH 2 SOLVER.BASE_LR 0.0025 SOLVER.MAX_ITER 720000 SOLVER.STEPS "(480000, 640000)" TEST.IMS_PER_BATCH 1 to train the model as it cannot reproduce the performance of the model zoo in maskrcnn-benchmark.

**Comment by gasvn** [comment]
Actually the maskrcnn-benchmark is deprecated now. We also  have the res2net+mmdetection and res2net+detectron2. You can use this two repos to achieve much better performance.

**Comment by aswa123** [comment]
So, now I cannot use single GPU?

**Comment by gasvn** [comment]
> So, now I cannot use single GPU?

You cannot reproduce the result with one GPU.

**Comment by aswa123** [comment]
So we cannot train with one GPU you mean?

**Comment by gasvn** [comment]
> So we cannot train with one GPU you mean?
yes

**Comment by aswa123** [comment]
What should I change if I want to use single GPU?
thank you.
